server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: gateway-service

logging:
  level:
    root: INFO

    org.springframework.cloud.gateway: WARN
    org.springframework.web.reactive: WARN

    reactor.netty: WARN
    reactor.netty.http.client: WARN
    reactor.netty.http.server: WARN

    com.netflix.discovery: WARN
    org.springframework.cloud.netflix.eureka: WARN

    org.springframework.boot.autoconfigure: ERROR
