server:
  port: 9000

spring:
  liquibase:
    enabled: false
    drop-first: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: off

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.netflix.discovery: ERROR
    org.springframework.cloud.netflix.eureka: ERROR
    org.apache.catalina: WARN
    com.work.auth: INFO

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true